apiVersion: v1
kind: Pod
metadata:
  name: ebpf
spec:
  containers:
  - name: ebpf-container
    image: docker.io/and22591/ebpf-docker-image:latest
    command: ["/bin/sh","-c"]
    args: ["mount -t debugfs none /sys/kernel/debug && cd libbpf-bootstrap/examples/c && ./minimal"]
      #args: ["mount -t debugfs none /sys/kernel/debug", "cd libbpf-bootstrap/examples/c && ./minimal"]
    securityContext:
      privileged: true


