apiVersion: apps/v1
#un pod per node
kind: DaemonSet
metadata:
  name: ebpf-daemonset
  labels:
    app: ebpf
spec:
  selector:
    matchLabels:
      app: ebpf
  template:
    metadata:
      labels:
        #deve essere uguale a selector.matchLables
        app: ebpf
    spec:
      containers:
      - name: ebpf-container
        #image: docker.io/and22591/ebpf-docker-image:latest
        image: docker.io/vladimiropaschali/ebpf-docker-image
        command: ["/bin/sh", "-c"]
        args: ["mount -t debugfs none /sys/kernel/debug && cd libbpf-bootstrap/examples/c && ./minimal_ns"]
        securityContext:
          privileged: true